### ISSUE TITLE
Ревью 1й дз: 24.03

### ISSUE THREAD

**Issue by YuriyBiznigaev** [vtezin/EpicSchoolHomework#1]
@vtezin 
1. установить min версию iOS Deployment Target = 14.0 в настройках проекта
![image](https://user-images.githubusercontent.com/75571475/159992212-4384869d-20b2-422e-a245-723be255878c.png)

2. убрать красный текст button из кнопки и оставить в нем только кликабельное изображение сердца.

**Comment by vtezin** [comment]
сделано

**Comment by stayn** [comment]
В целом всё ок, из доработок — сделать outlet'ы приватными (вот [почему](https://habr.com/ru/post/424843/)) и сделать склонение числительных более симпатичным способом [plurals](https://medium.com/@vitaliikuznetsov/%D0%BB%D0%BE%D0%BA%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-%D0%BC%D0%BD%D0%BE%D0%B6%D0%B5%D1%81%D1%82%D0%B2-%D0%B8%D0%BC%D0%B5%D0%BD-%D1%81%D1%83%D1%89%D0%B5%D1%81%D1%82%D0%B2%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D1%85-%D0%B2-ios-463dfe69048b) localization.

**Comment by vtezin** [comment]
доработки сделаны + сделана вторая домашка
(извиняюсь что не в отдельной ветке - с гитом разбираюсь пока)
